# Generated by Django 4.2.16 on 2025-12-06 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='main_author',
            field=models.ForeignKey(blank=True, help_text='Bu yayının ana yazarı', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_publications', to='core.researcher'),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_type',
            field=models.CharField(blank=True, help_text='journal / conference / thesis gibi tür bilgisi', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ResearcherSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('researcher', models.ForeignKey(db_column='researcher_id', on_delete=django.db.models.deletion.CASCADE, to='core.researcher')),
                ('skill', models.ForeignKey(db_column='skill_id', on_delete=django.db.models.deletion.CASCADE, to='core.skill')),
            ],
            options={
                'db_table': 'researcher_skill',
                'unique_together': {('researcher', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='ProjectResearcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text='Projede üstlendiği rol (PI, co-author, researcher vs.)', max_length=100, null=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('researcher', models.ForeignKey(db_column='researcher_id', on_delete=django.db.models.deletion.CASCADE, to='core.researcher')),
            ],
            options={
                'db_table': 'project_researcher',
                'unique_together': {('project', 'researcher')},
            },
        ),
    ]
