# Generated by Django 4.2.27 on 2025-12-07 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_authorpublication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='main_author',
        ),
        migrations.AddField(
            model_name='projectresearcher',
            name='contribution_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='projectresearcher',
            name='joined_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectresearcher',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectresearcher',
            name='project',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='core.project'),
        ),
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('invite', 'Davet (Gel Projeme Katıl)'), ('join_request', 'Katılım İsteği (Projene Katılabilir miyim?)')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('accepted', 'Kabul Edildi'), ('rejected', 'Reddedildi')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_requests', to='core.project')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='core.researcher')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='core.researcher')),
            ],
            options={
                'db_table': 'collaboration_request',
                'unique_together': {('sender', 'receiver', 'project')},
            },
        ),
    ]
