# Generated by Django 4.2.27 on 2025-12-08 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tag_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='test_field',
        ),
    ]
