# Generated by Django 4.2.27 on 2025-12-13 14:39

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
