# Generated by Django 4.2.16 on 2025-12-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_project_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='skills',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
