# Generated by Django 4.2.16 on 2025-12-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_researcher_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
