# Generated by Django 4.2.16 on 2025-12-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20251220_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectresearcher',
            name='project',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.project'),
        ),
        migrations.AlterField(
            model_name='researcherskill',
            name='researcher',
            field=models.ForeignKey(db_column='researcher_id', on_delete=django.db.models.deletion.CASCADE, related_name='researcher_skills', to='core.researcher'),
        ),
    ]
