# Generated by Django 4.2.16 on 2025-12-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_projectresearcher_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='suggestions_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
