# Generated by Django 4.2.16 on 2025-12-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_researcher_suggestions_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='request_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
