# Generated by Django 4.2.16 on 2025-12-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_notification_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
