# Generated by Django 4.2.16 on 2025-12-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_collaborationrequest_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AddField(
            model_name='project',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='phase',
            field=models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed')], default='planning', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
