# Generated by Django 4.2.16 on 2025-12-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_project_search_vector_alter_project_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='is_analyzing',
            field=models.BooleanField(default=False),
        ),
    ]
