# Generated by Django 4.2.x

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ------------------
        # Department
        # ------------------
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True, null=True, blank=True)),
                ('faculty', models.CharField(max_length=150, null=True, blank=True)),
            ],
            options={
                'db_table': 'department',
                'unique_together': {('name', 'faculty')},
            },
        ),

        # ------------------
        # FundingAgency
        # ------------------
        migrations.CreateModel(
            name='FundingAgency',
            fields=[
                ('funding_agency_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('country', models.CharField(max_length=100, null=True, blank=True)),
                ('website', models.CharField(max_length=255, null=True, blank=True)),
            ],
            options={
                'db_table': 'funding_agency',
            },
        ),

        # ------------------
        # Tag
        # ------------------
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tag',
            },
        ),

        # ------------------
        # Skill
        # ------------------
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'skill',
            },
        ),

        # ------------------
        # Researcher
        # ------------------
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('researcher_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('title', models.CharField(max_length=100, null=True, blank=True)),
                ('role', models.CharField(max_length=20, default='student')),
                ('bio', models.TextField(null=True, blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'user',
                    models.OneToOneField(
                        db_column='user_id',
                        null=True,
                        blank=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'department',
                    models.ForeignKey(
                        db_column='department_id',
                        null=True,
                        blank=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='researchers',
                        to='core.department',
                    ),
                ),
            ],
            options={
                'db_table': 'researcher',
            },
        ),

        # ------------------
        # Project
        # ------------------
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(null=True, blank=True)),
                ('status', models.CharField(max_length=20)),
                ('start_date', models.DateField(null=True, blank=True)),
                ('end_date', models.DateField(null=True, blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'department',
                    models.ForeignKey(
                        db_column='department_id',
                        null=True,
                        blank=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='projects',
                        to='core.department',
                    ),
                ),
                (
                    'pi',
                    models.ForeignKey(
                        db_column='pi_id',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='projects_as_pi',
                        to='core.researcher',
                    ),
                ),
            ],
            options={
                'db_table': 'project',
            },
        ),

        # ------------------
        # Publication
        # ------------------
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('publication_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=200, null=True, blank=True)),
                ('year', models.IntegerField(null=True, blank=True)),
                ('doi', models.CharField(max_length=100, null=True, blank=True)),
                (
                    'publication_type',
                    models.CharField(
                        max_length=50,
                        null=True,
                        blank=True,
                        help_text='journal / conference / thesis gibi tür bilgisi',
                    ),
                ),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'main_author',
                    models.ForeignKey(
                        null=True,
                        blank=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='main_publications',
                        to='core.researcher',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        db_column='project_id',
                        null=True,
                        blank=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='publications',
                        to='core.project',
                    ),
                ),
            ],
            options={
                'db_table': 'publication',
            },
        ),

        # ------------------
        # FundingAgencyGrant
        # ------------------
        migrations.CreateModel(
            name='FundingAgencyGrant',
            fields=[
                ('grant_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=200, null=True, blank=True)),
                ('amount', models.DecimalField(max_digits=18, decimal_places=2)),
                ('currency', models.CharField(max_length=10, default='TRY')),
                ('start_date', models.DateField(null=True, blank=True)),
                ('end_date', models.DateField(null=True, blank=True)),
                (
                    'funding_agency',
                    models.ForeignKey(
                        db_column='funding_agency_id',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='grants',
                        to='core.fundingagency',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        db_column='project_id',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='funding_grants',
                        to='core.project',
                    ),
                ),
            ],
            options={
                'db_table': 'funding_agency_grant',
                'unique_together': {('project', 'funding_agency', 'program_name')},
            },
        ),

        # ------------------
        # EntityTag
        # ------------------
        migrations.CreateModel(
            name='EntityTag',
            fields=[
                ('entity_tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=30)),
                ('entity_id', models.IntegerField()),
                (
                    'tag',
                    models.ForeignKey(
                        db_column='tag_id',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='entity_links',
                        to='core.tag',
                    ),
                ),
            ],
            options={
                'db_table': 'entity_tag',
                'unique_together': {('entity_type', 'entity_id', 'tag')},
            },
        ),

        # ------------------
        # ResearcherSkill
        # ------------------
        migrations.CreateModel(
            name='ResearcherSkill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                (
                    'level',
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text='Araştırmacının bu skilldeki seviyesi (1-5 arası)',
                    ),
                ),
                (
                    'researcher',
                    models.ForeignKey(
                        db_column='researcher_id',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='core.researcher',
                    ),
                ),
                (
                    'skill',
                    models.ForeignKey(
                        db_column='skill_id',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='core.skill',
                    ),
                ),
            ],
            options={
                'db_table': 'researcher_skill',
                'unique_together': {('researcher', 'skill')},
            },
        ),

        # ------------------
        # ProjectResearcher
        # ------------------
        migrations.CreateModel(
            name='ProjectResearcher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                (
                    'role',
                    models.CharField(
                        max_length=100,
                        null=True,
                        blank=True,
                        help_text='Projede üstlendiği rol (PI, co-author, researcher vs.)',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        db_column='project_id',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='core.project',
                    ),
                ),
                (
                    'researcher',
                    models.ForeignKey(
                        db_column='researcher_id',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='core.researcher',
                    ),
                ),
            ],
            options={
                'db_table': 'project_researcher',
                'unique_together': {('project', 'researcher')},
            },
        ),

        # ------------------
        # AuthorPublication
        # ------------------
        migrations.CreateModel(
            name='AuthorPublication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                (
                    'author_order',
                    models.PositiveSmallIntegerField(
                        null=True,
                        blank=True,
                        help_text='Yayındaki yazar sırası (1 = birinci yazar, 2 = ikinci vb.)',
                    ),
                ),
                (
                    'publication',
                    models.ForeignKey(
                        db_column='publication_id',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='core.publication',
                    ),
                ),
                (
                    'researcher',
                    models.ForeignKey(
                        db_column='researcher_id',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='core.researcher',
                    ),
                ),
            ],
            options={
                'db_table': 'author_publication',
                'unique_together': {('publication', 'researcher')},
            },
        ),
    ]
