# Generated by Django 4.2.16 on 2025-12-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_publication_main_author_publication_publication_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcherskill',
            name='level',
            field=models.PositiveSmallIntegerField(default=3, help_text='Araştırmacının bu skilldeki seviyesi (1-5 arası)'),
        ),
    ]
