# Generated by Django 4.2.16 on 2025-12-06 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_researcherskill_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_order', models.PositiveSmallIntegerField(blank=True, help_text='Yayındaki yazar sırası (1 = birinci yazar, 2 = ikinci vb.)', null=True)),
                ('publication', models.ForeignKey(db_column='publication_id', on_delete=django.db.models.deletion.CASCADE, to='core.publication')),
                ('researcher', models.ForeignKey(db_column='researcher_id', on_delete=django.db.models.deletion.CASCADE, to='core.researcher')),
            ],
            options={
                'db_table': 'author_publication',
                'unique_together': {('publication', 'researcher')},
            },
        ),
    ]
