# Generated by Django 4.2.27 on 2025-12-08 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_authorpublication'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectresearcher',
            name='contribution_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='projectresearcher',
            name='joined_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectresearcher',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectresearcher',
            name='project',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='core.project'),
        ),
    ]
