# Generated by Django 4.2.27 on 2025-12-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_projectresearcher_contribution_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, help_text='Test alanı', null=True),
        ),
    ]
