# Generated by Django 4.2.27 on 2025-12-08 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_publication_main_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='main_author',
            field=models.ForeignKey(blank=True, help_text='Bu yayının ana yazarı', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_publications', to='core.researcher'),
        ),
    ]
