# Generated by Django 4.2.27 on 2025-12-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_publication_main_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='test_field',
            field=models.BooleanField(default=False, help_text='Django kontrol testi'),
        ),
    ]
