# Generated by Django 4.2.27 on 2025-12-08 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tag_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
    ]
