# Generated by Django 4.2.27 on 2025-12-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_tag_test_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationrequest',
            name='response_message',
            field=models.TextField(blank=True, help_text='İsteği kabul/red eden kişinin notu', null=True),
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='message',
            field=models.TextField(blank=True, help_text='İsteği gönderen kişinin notu', null=True),
        ),
    ]
