"""
Django settings for research_backend project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import dj_database_url
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ze9%a7&&b9j1-l(nu=6a+fd$8!=+_c%+5u_fp=6pr0-n=$bsng'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# CSRF Güvenliği için (Render URL'ini sonra buraya ekleyeceğiz ama şimdilik genel izin)
CSRF_TRUSTED_ORIGINS = [
    "https://*.onrender.com",
    "https://real-assistans-for-academy.vercel.app",
    "https://reserchos.com.tr",
    "https://www.reserchos.com.tr"
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',

    # 3rd-party
    'jazzmin',
    'rest_framework',
    'corsheaders',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'core',
    'django_filters',
    
    'rest_framework_simplejwt',  # Token üretici
                   
    
]

# research_backend/settings.py

REST_FRAMEWORK = {
    # 1. Dokümantasyon (Swagger) için Gerekli Ayar (EKSİK OLAN BU)
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    # 2. Filtreleme, Arama ve Sıralama Ayarları
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],

    # 3. Sayfalama (Pagination)
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    # --- YENİ EKLENEN GÜVENLİK AYARLARI ---
    
    # Kimlik Doğrulama: Sadece JWT kabul et
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    
    # İzinler: Varsayılan olarak HER YER KİLİTLİ OLSUN (IsAuthenticated)
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),

}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # <-- EN ÜSTE BU!
    
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
     
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'research_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'research_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'research_platform',   # pgAdmin’de oluşturduğun DB adı
#         'USER': 'teammate',            # kendi postgres kullanıcın
#         'PASSWORD': 'Yusuf63123.',    # şifren
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }

# Render ve yeni domain izinleri
ALLOWED_HOSTS = [
    '*', 
    'reserchos.com.tr', 
    'www.reserchos.com.tr', 
    'real-assistans-for-academy-cbun.onrender.com'
]
DATABASES = {
    'default': dj_database_url.parse(
        # Link formatı: postgresql://postgres:[ŞİFREN]@db.[PROJE-KODU].supabase.co:5432/postgres
        # Şifreyi yazarken köşeli parantez [] kullanma!
        "postgresql://postgres.htjsmgqxsiajzxpqesdk:MehmetProject2025@aws-1-ap-south-1.pooler.supabase.com:6543/postgres",
        
        conn_max_age=600,
        ssl_require=True  # Bu satır Supabase bağlantısı için kritiktir
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'










# CORS AYARLARI
CORS_ALLOW_ALL_ORIGINS = True


from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # Anahtar 60 dk geçerli
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),     # Yenileme anahtarı 1 gün
    'AUTH_HEADER_TYPES': ('Bearer',),                # Anahtar kelime
}




SPECTACULAR_SETTINGS = {
    'TITLE': 'Research Platform API',
    'DESCRIPTION': 'Academic Research Management System',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # Swagger UI'da kilit butonunu aktif et
    'COMPONENT_SPLIT_REQUEST': True,
    'SECURITY': [{'Bearer': []}],         
}

# settings.py dosyasının en altı

# Google Gemini API Key
GEMINI_API_KEY = "AIzaSyBHyXfXs6fkbcFRyr7JU1JLLnKvQYua394"



# --- CORS AYARLARI (React İzni) ---
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://real-assistans-for-academy.vercel.app",
    "https://reserchos.com.tr",
    "https://www.reserchos.com.tr" # Sonuna virgül eklemeyi unutma
]